# Generated by Django 5.0.1 on 2024-02-23 11:12

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=200),
        ),
    ]
