# Generated by Django 5.0.1 on 2024-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='conpassword',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
