# Generated by Django 5.0.1 on 2024-02-29 10:17

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='prices',
            field=django_mysql.models.ListTextField(models.CharField(default='None', max_length=255), default='None', size=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='classes',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
