# Generated by Django 5.0.1 on 2024-02-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menu_prices_alter_booking_phone_alter_classes_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='prices',
            field=models.DecimalField(decimal_places=2, default='None', max_digits=5),
        ),
    ]
