# Generated by Django 5.0.1 on 2024-02-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menu_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='prices',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
