# Generated by Django 5.0.1 on 2024-02-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_menu_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
