# Generated by Django 5.0.1 on 2024-02-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_date_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 20, 11, 5, 8, 680792)),
        ),
    ]
