# Generated by Django 5.0.1 on 2024-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_booking_date_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
