# Generated by Django 5.0.1 on 2024-02-22 11:40

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default='None', max_length=66, size=None),
        ),
    ]
