# Generated by Django 5.0.1 on 2024-02-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_menu_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu Order', 'verbose_name_plural': 'Menu Orders'},
        ),
        migrations.AddField(
            model_name='menu',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
